services:
  - type: web
    name: meditacion-valeria
    env: static
    runtime: node
    buildCommand: npm install --legacy-peer-deps && npm run build
    staticPublishPath: ./dist
    headers:
      - path: /*
        name: Cache-Control
        value: max-age=31536000, immutable
